name: whats_up_ui
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: any
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Averta
      fonts:
        - asset: fonts/averta.ttf
    - family: Regular
      fonts:
        - asset: fonts/averta-regular.ttf
    - family: Italic
      fonts:
        - asset: fonts/averta-regularitalic.ttf
    - family: Bold
      fonts:
        - asset: fonts/averta-bold.ttf
    - family: Bold Italic
      fonts:
        - asset: fonts/averta-bolditalic.ttf
    - family: Extra
      fonts:
        - asset: fonts/averta-extrabold.ttf
    - family: Extra Italic
      fonts:
        - asset: fonts/averta-extrabolditalic.ttf
    - family: Light
      fonts:
        - asset: fonts/averta-light.ttf
    - family: Light Italic
      fonts:
        - asset: fonts/averta-lightitalic.ttf
    - family: Semibold
      fonts:
        - asset: fonts/averta-semibold.ttf
    - family: Semibold Italic
      fonts:
        - asset: fonts/averta-semibolditalic.ttf
    - family: Thin
      fonts:
        - asset: fonts/averta-thin.ttf
    - family: Thin Italic
      fonts:
        - asset: fonts/averta-thinitalic.ttf
    - family: Light
      fonts:
        - asset: fonts/averta-light.ttf
    - family: Light Italic
      fonts:
        - asset: fonts/averta-lightitalic.ttf
    - family: Black
      fonts:
        - asset: fonts/averta-black.ttf
    - family: Black Italic
      fonts:
        - asset: fonts/averta-blackitalic.ttf
    - family: Clight
      fonts:
        - asset: fonts/AvertaCY-Light.ttf
    - family: Cregular
      fonts:
        - asset: fonts/AvertaCY-Regular.ttf
    - family: Csemibold
      fonts:
        - asset: fonts/AvertaCY-Semibold.ttf
    - family: Cbold
      fonts:
        - asset: fonts/AvertaDemoPE-ExtraBold.otf
    - family: Ccutted
      fonts:
        - asset: fonts/AvertaDemoPeCuttedDemo-Regular.otf
    - family: CustomIcon
      fonts:
        - asset: fonts/CustomIcon.ttf
